name: clv_predictive_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.17
  - scipy
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pymc-marketing
  - streamlit
  - scikit-learn
  - u8darts-notorch
  - pip:
    - torch
    - torchvision
    - torchaudio
    - jax[cuda12]
    - numpyro